.test: &test
  if: build.message !~ /\[skip tests\]/
  agents:
    queue: "juliaecosystem"
    sandbox.jl: "true"
    os: linux
    arch: x86_64
.bench: &bench
  if: build.message =~ /\[run benchmarks\]/
  agents:
    queue: "juliaecosystem"
    sandbox.jl: "true"
    os: linux
    arch: x86_64
    num_cpus: 16
steps:
  - label: Julia 1.7
    timeout_in_minutes: 60
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Julia 1.8
    timeout_in_minutes: 60
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.8"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Julia nightly
    timeout_in_minutes: 60
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9-nightly"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Julia 1.6 (macOS)
    timeout_in_minutes: 60
    <<: *test
    agents:
      queue: "juliaecosystem"
      os: macos
      arch: x86_64
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Benchmarks
    timeout_in_minutes: 120
    <<: *bench
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-test#v1:
          run_tests: false
    command: "julia -e 'using Pkg; Pkg.add(\"BenchmarkTools\"); Pkg.develop(;path=pwd())'; JULIA_PROJECT=\"$PWD\" julia --project benchmarks/benchmark.jl"
    env:
      JULIA_NUM_THREADS: "4"
      BENCHMARK: "cpu,cpu+dagger"
      BENCHMARK_PROCS: "4:4"
      BENCHMARK_SCALE: "5:5:50"
    artifacts:
      - benchmarks/result*
