name: Trigger benchmarks
on: workflow_dispatch
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl https://api.buildkite.com/v2/organizations/julialang/pipelines/dagger-dot-jl/builds \
            --header "Authorization: Bearer $BUILDKITE_TOKEN" \
            --data '{"commit": "HEAD", "branch": "master", "env": {"DAGGER_BENCHMARK": "true"}}' \
          | jq -r .web_url
        env:
          BUILDKITE_TOKEN: ${{ secrets.BUILDKITE_TOKEN }}
